// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZo6h73uHayg_aLGVTVuj8YO-uP3vu-TQ',
    appId: '1:29572786777:web:173d9f87667b5ba63c1f48',
    messagingSenderId: '29572786777',
    projectId: 'spiderwebforecast',
    authDomain: 'spiderwebforecast.firebaseapp.com',
    storageBucket: 'spiderwebforecast.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUFpW6fobWWv7Yntm0PZf9-ohdhz0oj1g',
    appId: '1:29572786777:android:3c3a96df4822f87e3c1f48',
    messagingSenderId: '29572786777',
    projectId: 'spiderwebforecast',
    storageBucket: 'spiderwebforecast.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVey8v4qBLnaroW1dvxAWV_DbJWmhmjmM',
    appId: '1:29572786777:ios:2583385d045288a43c1f48',
    messagingSenderId: '29572786777',
    projectId: 'spiderwebforecast',
    storageBucket: 'spiderwebforecast.appspot.com',
    iosBundleId: 'com.example.spiderwebforecast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZo6h73uHayg_aLGVTVuj8YO-uP3vu-TQ',
    appId: '1:29572786777:web:ff47db71b70d7b3d3c1f48',
    messagingSenderId: '29572786777',
    projectId: 'spiderwebforecast',
    authDomain: 'spiderwebforecast.firebaseapp.com',
    storageBucket: 'spiderwebforecast.appspot.com',
  );
}
